name: Release Go project

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go ^1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Get dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Test with Coverage
        run: go test -v  -coverprofile='coverage.txt' -covermode=atomic ./...

      - name: Upload Codecov
        uses: codecov/codecov-action@v1.0.14
        if: success()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run Vet & Lint
        run: |
          go vet ./...
          golint -set_exit_status=1 ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        if: success()
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
          
